### ISSUE TITLE
Remove unnecessary commas from JSON format

### ISSUE THREAD

**Issue by cenation092** [VenkatPantham/edyst-s19-create-your-own-pokemon#4]
pokemondata = {
        "pokemon": {
            "id": pokemon.id,
            "name": pokemon.name,
            "sprite": pokemon.sprite,
            "cardColours": {"fg": pokemon.fg, "bg": pokemon.bg, "desc": pokemon.desc}, **#like this**
        }
    }

Refer this: https://stackoverflow.com/questions/13675401/cant-read-json-file-in-python

**Comment by VenkatPantham** [comment]
Removed all the unnecessary comas
